### ISSUE TITLE
Holodeck (develop) crashing when running an episode for many steps.

### ISSUE THREAD

**Issue by nickwalton** [BYU-PCCL/holodeck-engine#68]
When running an episode for 3000 steps before resetting the environment the holodeck eventually crashes on the develop branch.

**Comment by mitchneutron** [comment]
Specifically, it crashes during 1821st iteration. The problem was introduced with the command center commit (34780b37a53c61e71dc568d1287d923c94e038e5). Said build crashes when doing longer episodes (>1820 steps), while the commit immediately preceding it (b2dd0a1bb1f5bc38aed2a90f8fdd71516b9b25d3) does not crash when performing the same or longer episode length.
